/**
 * Конфигурация Rollup для Chrome Extension
 */

export default {
  input: 'src/main.js',
  output: {
    file: 'dist/content.js',
    format: 'iife', // Immediately Invoked Function Expression - подходит для content scripts
    name: 'JiraWorklogReporter',
    banner: '/* Jira Worklog Reporter - Chrome Extension */\n/* Generated by Rollup */',
    sourcemap: false // Отключаем sourcemap для production
  },
  plugins: [
    // Пока без плагинов - Rollup отлично работает с ES6 из коробки
  ],
  // Предупреждения, которые можно игнорировать в контексте Chrome extension
  onwarn: (warning, warn) => {
    // Игнорируем предупреждения о циклических зависимостях, если они есть
    if (warning.code === 'CIRCULAR_DEPENDENCY') return;
    warn(warning);
  }
};